import type { Metadata } from "next";

//component
import Toolbar from "@/component/toolbar/toolbar";
import Footer from "@/component/footer/footer";

// global style
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toolbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
